using System;

namespace _389._Find_the_Difference
{
    /// <summary>
    /// You are given two strings s and t.String t is generated by random shuffling string s and then add one more letter at a random position.Return the letter that was added to t.
    /// </summary>
    internal class Program
    {
        static void Main(string[] args)
        {
           string s = "abcd", t = "abcde";


            string haystack = "leetcode", needle = "leeto";

            var res = haystack.Contains(needle);
            Console.WriteLine(res);
            Console.WriteLine(Solution.FindTheDifference(s, t));
        }

        public class Solution
        {
            public static char FindTheDifference(string s, string t)
            {


                var combinedString = s + t;

                foreach (char c in combinedString)
                {
                    int count = 0;

                    foreach (char innerChar in combinedString)
                    {
                        if (c == innerChar)
                            count++;
                    }

                    if (count == 1)
                        return c;
                }

                return '\0'; // Возвращаем пустой символ, если уникальный символ не найден

                //var arrS = s.ToCharArray().ToList();
                //    var arrT = t.ToCharArray().ToList();

                //    var list = arrT.ToList();

                //    for (int i = 0; i < arrT.Count; i++)
                //    {
                //        for (int j = 0; j < arrS.Count; j++)
                //        {
                //            if (i == arrS.Count) break;
                //            if (arrS[i] == arrT[i])
                //            {
                //                list.Remove(arrS[i]);
                //            }
                //        }
                //    }

                //for (int i = 0; i < arrT.Count; i++)
                //{
                //    if (i == arrS.Count) break;
                //    if (arrS[i] == arrT[i])
                //    {
                //        list.Remove(arrT[i]);
                //    }
                //}

            }
        }
    }
}